version: '3.7'

services:
  polystore:
    restart: always
    image: clms/typhon-polystore-api:latest
    hostname: polystore-api
    container_name: typhon-polystore-service
    ports:
      - "8080:8080"
    volumes:
     - "./models:/models"
    depends_on:
      - polystoredb
  polystore_ui:
    image: clms/typhon-polystore-ui:latest
    environment:
      API_HOST: localhost
      API_PORT: 8080
    container_name: polystore-ui
    ports:
      - 4200:4200
    restart: always
    hostname: polystore-ui
  polystoredb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    container_name: polystore-mongo
    hostname: polystore-api-db
    ports:
      - 27017:27017
